-- Migration: Purge Dummy & Mock Data
-- Description: Completely deletes all fake trees and projects generated by the old prototype "Smart Grid" tool.

-- 1. Delete all fake projects containing 'test', 'demo', 'asdf'
DELETE FROM public.plantation_projects
WHERE project_name ILIKE '%test%'
   OR project_name ILIKE '%demo%'
   OR project_name ILIKE '%asdf%'
   OR project_name ILIKE '%dummy%';

-- 2. Clear out fake AI bulk grids from any remaining projects
UPDATE public.plantation_projects
SET bulk_data = '[]'::jsonb,
    bulk_rows = 0
WHERE bulk_data::text ILIKE '%GE-00%';

-- 3. Delete any orphaned evidence audits
DELETE FROM public.observation_evidence_audit
WHERE tree_id NOT IN (SELECT id FROM public.trees);
